/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import controller.ControllerUser;
import java.util.ArrayList;
import javax.swing.JComboBox;

/**
 *
 * @author Formation
 */
public class UseurView extends javax.swing.JPanel {
  ControllerUser controleruser ;
  
    /**
     * Creates new form Useur
     */
    public UseurView(ControllerUser controleruser) {
        initComponents();
        this.controleruser=controleruser;
        jt_listUser = this.controleruser.addRowTable(jt_listUser);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jp_tableUseur = new javax.swing.JPanel();
        jScrollTableUseur = new javax.swing.JScrollPane();
        jt_listUser = new javax.swing.JTable();
        jp_gestionUtilisateur = new javax.swing.JPanel();
        jb_Reinitialiser = new javax.swing.JButton();
        jb_Supprimer = new javax.swing.JButton();
        jl_Prénom = new javax.swing.JLabel();
        jl_Nom = new javax.swing.JLabel();
        jl_Pseudo = new javax.swing.JLabel();
        jt_Prénom = new javax.swing.JTextField();
        jt_Nom = new javax.swing.JTextField();
        jt_Pseudo = new javax.swing.JTextField();
        jb_Mettre_à_Jour = new javax.swing.JButton();
        jl_Metier = new javax.swing.JLabel();
        jl_Mot_de_Passe = new javax.swing.JLabel();
        jcb_Admin = new javax.swing.JCheckBox();
        jcb_Bloqués = new javax.swing.JCheckBox();
        jp_Mot_de_Passe = new javax.swing.JPasswordField();
        cb_Metier = new javax.swing.JComboBox<>();
        jl_Ville = new javax.swing.JLabel();
        jl_Pays = new javax.swing.JLabel();
        jl_Tel = new javax.swing.JLabel();
        jl_Mail = new javax.swing.JLabel();
        jl_Adress = new javax.swing.JLabel();
        jt_Ville = new javax.swing.JTextField();
        jt_Pays = new javax.swing.JTextField();
        jt_Tel = new javax.swing.JTextField();
        jt_Mail = new javax.swing.JTextField();
        jt_Adress = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1024, 768));
        setLayout(new java.awt.GridLayout(2, 1));

        jp_tableUseur.setLayout(new java.awt.GridLayout(1, 0));

        jt_listUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nom", "Prénom", "Address", "Ville", "Pays", "Tel", "Mail", "Metier", "pseudo_site", "Bloqué", "Admin", "pseudo_back"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt_listUser.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jt_listUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_listUserMouseClicked(evt);
            }
        });
        jScrollTableUseur.setViewportView(jt_listUser);
        if (jt_listUser.getColumnModel().getColumnCount() > 0) {
            jt_listUser.getColumnModel().getColumn(0).setResizable(false);
            jt_listUser.getColumnModel().getColumn(1).setResizable(false);
            jt_listUser.getColumnModel().getColumn(2).setResizable(false);
            jt_listUser.getColumnModel().getColumn(3).setResizable(false);
            jt_listUser.getColumnModel().getColumn(4).setResizable(false);
            jt_listUser.getColumnModel().getColumn(5).setResizable(false);
            jt_listUser.getColumnModel().getColumn(6).setResizable(false);
            jt_listUser.getColumnModel().getColumn(7).setResizable(false);
            jt_listUser.getColumnModel().getColumn(8).setResizable(false);
            jt_listUser.getColumnModel().getColumn(9).setResizable(false);
            jt_listUser.getColumnModel().getColumn(10).setResizable(false);
            jt_listUser.getColumnModel().getColumn(11).setResizable(false);
            jt_listUser.getColumnModel().getColumn(12).setResizable(false);
        }

        jp_tableUseur.add(jScrollTableUseur);

        add(jp_tableUseur);

        jp_gestionUtilisateur.setPreferredSize(new java.awt.Dimension(45, 16));
        jp_gestionUtilisateur.setLayout(new java.awt.GridBagLayout());

        jb_Reinitialiser.setText("Reinitialiser");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jb_Reinitialiser, gridBagConstraints);

        jb_Supprimer.setText("Supprimer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jb_Supprimer, gridBagConstraints);

        jl_Prénom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_Prénom.setText("Prénom");
        jl_Prénom.setToolTipText("");
        jl_Prénom.setPreferredSize(new java.awt.Dimension(106, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jl_Prénom, gridBagConstraints);

        jl_Nom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_Nom.setText("Nom");
        jl_Nom.setToolTipText("");
        jl_Nom.setPreferredSize(new java.awt.Dimension(106, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jl_Nom, gridBagConstraints);

        jl_Pseudo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_Pseudo.setText("Pseudo");
        jl_Pseudo.setToolTipText("");
        jl_Pseudo.setPreferredSize(new java.awt.Dimension(106, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jl_Pseudo, gridBagConstraints);

        jt_Prénom.setMinimumSize(new java.awt.Dimension(150, 20));
        jt_Prénom.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jt_Prénom, gridBagConstraints);

        jt_Nom.setMinimumSize(new java.awt.Dimension(150, 20));
        jt_Nom.setPreferredSize(new java.awt.Dimension(150, 20));
        jt_Nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_NomActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jt_Nom, gridBagConstraints);

        jt_Pseudo.setMinimumSize(new java.awt.Dimension(150, 20));
        jt_Pseudo.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jt_Pseudo, gridBagConstraints);

        jb_Mettre_à_Jour.setText("Mettre à Jour");
        jb_Mettre_à_Jour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_Mettre_à_JourActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jb_Mettre_à_Jour, gridBagConstraints);

        jl_Metier.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_Metier.setText("Metier");
        jl_Metier.setPreferredSize(new java.awt.Dimension(106, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jl_Metier, gridBagConstraints);

        jl_Mot_de_Passe.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_Mot_de_Passe.setText("Mot de Passe");
        jl_Mot_de_Passe.setPreferredSize(new java.awt.Dimension(106, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jl_Mot_de_Passe, gridBagConstraints);

        jcb_Admin.setText("Admin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jcb_Admin, gridBagConstraints);

        jcb_Bloqués.setText("Bloqués");
        jcb_Bloqués.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_BloquésActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jcb_Bloqués, gridBagConstraints);

        jp_Mot_de_Passe.setMinimumSize(new java.awt.Dimension(150, 20));
        jp_Mot_de_Passe.setPreferredSize(new java.awt.Dimension(150, 20));
        jp_Mot_de_Passe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jp_Mot_de_PasseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jp_Mot_de_Passe, gridBagConstraints);

        cb_Metier.setMinimumSize(new java.awt.Dimension(150, 20));
        cb_Metier.setPreferredSize(new java.awt.Dimension(150, 20));
        cb_Metier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_MetierActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(cb_Metier, gridBagConstraints);

        jl_Ville.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_Ville.setText("Ville");
        jl_Ville.setPreferredSize(new java.awt.Dimension(106, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jl_Ville, gridBagConstraints);

        jl_Pays.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_Pays.setText("Pays");
        jl_Pays.setPreferredSize(new java.awt.Dimension(106, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jl_Pays, gridBagConstraints);

        jl_Tel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_Tel.setText("Tel");
        jl_Tel.setPreferredSize(new java.awt.Dimension(106, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jl_Tel, gridBagConstraints);

        jl_Mail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_Mail.setText("Mail");
        jl_Mail.setPreferredSize(new java.awt.Dimension(106, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jl_Mail, gridBagConstraints);

        jl_Adress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_Adress.setText("Adress");
        jl_Adress.setPreferredSize(new java.awt.Dimension(106, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jl_Adress, gridBagConstraints);

        jt_Ville.setMinimumSize(new java.awt.Dimension(150, 20));
        jt_Ville.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jt_Ville, gridBagConstraints);

        jt_Pays.setMinimumSize(new java.awt.Dimension(150, 20));
        jt_Pays.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jt_Pays, gridBagConstraints);

        jt_Tel.setMinimumSize(new java.awt.Dimension(150, 20));
        jt_Tel.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jt_Tel, gridBagConstraints);

        jt_Mail.setMinimumSize(new java.awt.Dimension(150, 20));
        jt_Mail.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jt_Mail, gridBagConstraints);

        jt_Adress.setMinimumSize(new java.awt.Dimension(150, 20));
        jt_Adress.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jt_Adress, gridBagConstraints);

        add(jp_gestionUtilisateur);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_Mettre_à_JourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_Mettre_à_JourActionPerformed
        
    }//GEN-LAST:event_jb_Mettre_à_JourActionPerformed

    private void jcb_BloquésActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_BloquésActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_BloquésActionPerformed

    private void jp_Mot_de_PasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jp_Mot_de_PasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jp_Mot_de_PasseActionPerformed
    
    
    private void jt_listUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_listUserMouseClicked
         
        if (evt.getClickCount() == 1) {
                // get id of the flight selected
            Object numObject = jt_listUser.getValueAt(jt_listUser.getSelectedRow(), 0);
            Long id = Long.parseLong(numObject.toString());
            
            // Add file selected in textfield
            this.controleruser.UserInfo(this,id);
            
        }
    }//GEN-LAST:event_jt_listUserMouseClicked

    private void cb_MetierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_MetierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_MetierActionPerformed

    private void jt_NomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_NomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_NomActionPerformed
    
     public void updateInfoPlanned(ArrayList<String> values){
//        jt_Nom.setText(values.get(0));
//        jt_Prénom.setText(values.get(1));
//        jt_Pseudo.setText(values.get(2));
//        jp_Mot_de_Passe.setText(values.get(3));
//        setSelectedValue(cb_Metier, values.get(4));
//        jcb_Admin.setText(values.get(5));
//        jcb_Bloqués.setText(values.get(6));
//        jt_Ville.setText(values.get(7));
//        jt_Pays.setText(values.get(8));
//        jt_Tel.setText(values.get(9));
//        jt_Mail.setText(values.get(10));
//        jl_Adress.setText(values.get(11));
//        
        
        
        
    }
    
    public static void setSelectedValue(JComboBox comboBox, String value)
    {
//        for(int i = 0; i < comboBox.getItemCount(); i++){
//            if(comboBox.getItemAt(i).equals(value)){
//                comboBox.setSelectedIndex(i);
//                break;
//            } else{
//                setSelectedValue(comboBox, "");
//            }
//                
//        }
//        
      
    }
    public void updateUserInfo(ArrayList<String> values,ArrayList<Boolean> valuesBollean){
        
       
        jt_Nom.setText(values.get(0));
        jt_Prénom.setText(values.get(1));
        jt_Adress.setText(values.get(2));
        jt_Ville.setText(values.get(3));
        jt_Pays.setText(values.get(4));
        jt_Tel.setText(values.get(5));
        jt_Mail.setText(values.get(6));
//        cb_Metier.setSelectedIndex(values.get(7));
//        tf_dateArrived.setText(values.get(8));
        
//        tf_price.setText(values.get(9));

        jcb_Bloqués.setSelected((boolean)valuesBollean.get(0));
        jcb_Admin.setSelected((boolean)valuesBollean.get(1));

        
        
        System.out.println((boolean)valuesBollean.get(0));
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_Metier;
    private javax.swing.JScrollPane jScrollTableUseur;
    private javax.swing.JButton jb_Mettre_à_Jour;
    private javax.swing.JButton jb_Reinitialiser;
    private javax.swing.JButton jb_Supprimer;
    private javax.swing.JCheckBox jcb_Admin;
    private javax.swing.JCheckBox jcb_Bloqués;
    private javax.swing.JLabel jl_Adress;
    private javax.swing.JLabel jl_Mail;
    private javax.swing.JLabel jl_Metier;
    private javax.swing.JLabel jl_Mot_de_Passe;
    private javax.swing.JLabel jl_Nom;
    private javax.swing.JLabel jl_Pays;
    private javax.swing.JLabel jl_Prénom;
    private javax.swing.JLabel jl_Pseudo;
    private javax.swing.JLabel jl_Tel;
    private javax.swing.JLabel jl_Ville;
    private javax.swing.JPasswordField jp_Mot_de_Passe;
    private javax.swing.JPanel jp_gestionUtilisateur;
    private javax.swing.JPanel jp_tableUseur;
    private javax.swing.JTextField jt_Adress;
    private javax.swing.JTextField jt_Mail;
    private javax.swing.JTextField jt_Nom;
    private javax.swing.JTextField jt_Pays;
    private javax.swing.JTextField jt_Prénom;
    private javax.swing.JTextField jt_Pseudo;
    private javax.swing.JTextField jt_Tel;
    private javax.swing.JTextField jt_Ville;
    private javax.swing.JTable jt_listUser;
    // End of variables declaration//GEN-END:variables

}
