/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;

/**
 *
 * @author Formation
 */
public class Useur extends javax.swing.JPanel {

    /**
     * Creates new form Useur
     */
    public Useur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jp_tableUseur = new javax.swing.JPanel();
        jScrollTableUseur = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jp_gestionUtilisateur = new javax.swing.JPanel();
        jb_Reinitialiser = new javax.swing.JButton();
        jb_Supprimer = new javax.swing.JButton();
        jl_Prénom = new javax.swing.JLabel();
        jl_Nom = new javax.swing.JLabel();
        jl_Pseudo = new javax.swing.JLabel();
        jt_Prénom = new javax.swing.JTextField();
        jt_Nom = new javax.swing.JTextField();
        jt_Pseudo = new javax.swing.JTextField();
        jb_Mettre_à_Jour = new javax.swing.JButton();
        jl_Metier = new javax.swing.JLabel();
        jl_Mot_de_Passe = new javax.swing.JLabel();
        jcb_Admine = new javax.swing.JCheckBox();
        jcb_Bloqués = new javax.swing.JCheckBox();
        jp_Mot_de_Passe = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jl_Ville = new javax.swing.JLabel();
        jl_Pays = new javax.swing.JLabel();
        jl_Tel = new javax.swing.JLabel();
        jl_Mail = new javax.swing.JLabel();
        jl_Adress = new javax.swing.JLabel();
        jt_Ville = new javax.swing.JTextField();
        jt_Pays = new javax.swing.JTextField();
        jt_Tel = new javax.swing.JTextField();
        jt_Mail = new javax.swing.JTextField();
        jt_Adress = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1024, 768));
        setLayout(new java.awt.GridLayout(2, 1));

        jp_tableUseur.setLayout(new java.awt.GridLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nom", "Prénom", "Pseudo", "Ville", "Pays", "Tel", "Mail", "Metier", "Address", "Admine", "Bloqué"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollTableUseur.setViewportView(jTable1);

        jp_tableUseur.add(jScrollTableUseur);

        add(jp_tableUseur);

        jp_gestionUtilisateur.setPreferredSize(new java.awt.Dimension(45, 16));
        jp_gestionUtilisateur.setLayout(new java.awt.GridBagLayout());

        jb_Reinitialiser.setText("Reinitialiser");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jb_Reinitialiser, gridBagConstraints);

        jb_Supprimer.setText("Supprimer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jb_Supprimer, gridBagConstraints);

        jl_Prénom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_Prénom.setText("Prénom");
        jl_Prénom.setToolTipText("");
        jl_Prénom.setPreferredSize(new java.awt.Dimension(106, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jl_Prénom, gridBagConstraints);

        jl_Nom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_Nom.setText("Nom");
        jl_Nom.setToolTipText("");
        jl_Nom.setPreferredSize(new java.awt.Dimension(106, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jl_Nom, gridBagConstraints);

        jl_Pseudo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_Pseudo.setText("Pseudo");
        jl_Pseudo.setToolTipText("");
        jl_Pseudo.setPreferredSize(new java.awt.Dimension(106, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jl_Pseudo, gridBagConstraints);

        jt_Prénom.setText("jTextField1");
        jt_Prénom.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jt_Prénom, gridBagConstraints);

        jt_Nom.setText("jTextField2");
        jt_Nom.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jt_Nom, gridBagConstraints);

        jt_Pseudo.setText("jTextField3");
        jt_Pseudo.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jt_Pseudo, gridBagConstraints);

        jb_Mettre_à_Jour.setText("Mettre à Jour");
        jb_Mettre_à_Jour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_Mettre_à_JourActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jb_Mettre_à_Jour, gridBagConstraints);

        jl_Metier.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_Metier.setText("Metier");
        jl_Metier.setPreferredSize(new java.awt.Dimension(106, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jl_Metier, gridBagConstraints);

        jl_Mot_de_Passe.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_Mot_de_Passe.setText("Mot de Passe");
        jl_Mot_de_Passe.setPreferredSize(new java.awt.Dimension(106, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jl_Mot_de_Passe, gridBagConstraints);

        jcb_Admine.setText("Admine");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jcb_Admine, gridBagConstraints);

        jcb_Bloqués.setText("Bloqués");
        jcb_Bloqués.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_BloquésActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jcb_Bloqués, gridBagConstraints);

        jp_Mot_de_Passe.setText("jPasswordField1");
        jp_Mot_de_Passe.setPreferredSize(new java.awt.Dimension(150, 20));
        jp_Mot_de_Passe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jp_Mot_de_PasseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jp_Mot_de_Passe, gridBagConstraints);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jComboBox1, gridBagConstraints);

        jl_Ville.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_Ville.setText("Ville");
        jl_Ville.setPreferredSize(new java.awt.Dimension(106, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jl_Ville, gridBagConstraints);

        jl_Pays.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_Pays.setText("Pays");
        jl_Pays.setPreferredSize(new java.awt.Dimension(106, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jl_Pays, gridBagConstraints);

        jl_Tel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_Tel.setText("Tel");
        jl_Tel.setPreferredSize(new java.awt.Dimension(106, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jl_Tel, gridBagConstraints);

        jl_Mail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_Mail.setText("Mail");
        jl_Mail.setPreferredSize(new java.awt.Dimension(106, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jl_Mail, gridBagConstraints);

        jl_Adress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_Adress.setText("Adress");
        jl_Adress.setPreferredSize(new java.awt.Dimension(106, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jl_Adress, gridBagConstraints);

        jt_Ville.setText("jTextField1");
        jt_Ville.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jt_Ville, gridBagConstraints);

        jt_Pays.setText("jTextField2");
        jt_Pays.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jt_Pays, gridBagConstraints);

        jt_Tel.setText("jTextField3");
        jt_Tel.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jt_Tel, gridBagConstraints);

        jt_Mail.setText("jTextField4");
        jt_Mail.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jt_Mail, gridBagConstraints);

        jt_Adress.setText("jTextField5");
        jt_Adress.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 12);
        jp_gestionUtilisateur.add(jt_Adress, gridBagConstraints);

        add(jp_gestionUtilisateur);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_Mettre_à_JourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_Mettre_à_JourActionPerformed
        
    }//GEN-LAST:event_jb_Mettre_à_JourActionPerformed

    private void jcb_BloquésActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_BloquésActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_BloquésActionPerformed

    private void jp_Mot_de_PasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jp_Mot_de_PasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jp_Mot_de_PasseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollTableUseur;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jb_Mettre_à_Jour;
    private javax.swing.JButton jb_Reinitialiser;
    private javax.swing.JButton jb_Supprimer;
    private javax.swing.JCheckBox jcb_Admine;
    private javax.swing.JCheckBox jcb_Bloqués;
    private javax.swing.JLabel jl_Adress;
    private javax.swing.JLabel jl_Mail;
    private javax.swing.JLabel jl_Metier;
    private javax.swing.JLabel jl_Mot_de_Passe;
    private javax.swing.JLabel jl_Nom;
    private javax.swing.JLabel jl_Pays;
    private javax.swing.JLabel jl_Prénom;
    private javax.swing.JLabel jl_Pseudo;
    private javax.swing.JLabel jl_Tel;
    private javax.swing.JLabel jl_Ville;
    private javax.swing.JPasswordField jp_Mot_de_Passe;
    private javax.swing.JPanel jp_gestionUtilisateur;
    private javax.swing.JPanel jp_tableUseur;
    private javax.swing.JTextField jt_Adress;
    private javax.swing.JTextField jt_Mail;
    private javax.swing.JTextField jt_Nom;
    private javax.swing.JTextField jt_Pays;
    private javax.swing.JTextField jt_Prénom;
    private javax.swing.JTextField jt_Pseudo;
    private javax.swing.JTextField jt_Tel;
    private javax.swing.JTextField jt_Ville;
    // End of variables declaration//GEN-END:variables

}
